# version: '3.9'

# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: sdp_db
#       POSTGRES_USER: sdp_user
#       POSTGRES_PASSWORD: sdp_password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - sdp_network

#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
#     volumes:
#       - .:/SDP
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://sdp_user:sdp_password@db:5432/sdp_db
#     networks:
#       - sdp_network

# volumes:
#   postgres_data:

# networks:
#   sdp_network:


# version: '3.9'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/SDP
#     ports:
#       - "${HOST_PORT:-8000}:8000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgres://postgres:password@db:5432/sdp_db
#       - DJANGO_ALLOWED_HOSTS=localhost

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: sdp_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password

# volumes:
#   postgres_data:

version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/SDP
    ports:
      - "${HOST_PORT:-8000}:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/sdp_db
      - DJANGO_ALLOWED_HOSTS=localhost,sdp.boisestate.edu
      - APP_ROOT=${APP_ROOT:-}  
      - CSRF_TRUSTED_ORIGINS=https://*.127.0.0.1,https://sdp.boisestate.edu
    networks:
      - sdp_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sdp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - sdp_network

volumes:
  postgres_data:

networks:
  sdp_network:
    driver: bridge