# Generated by Django 5.1.1 on 2024-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_abbreviation', models.CharField(default='Team', max_length=100)),
                ('Location', models.CharField(default='Location', max_length=100)),
                ('Poster_title', models.CharField(default='Title', max_length=255)),
                ('Abstract', models.TextField(default='Abstract')),
                ('num_team_members', models.IntegerField(default=1)),
                ('team_member_names', models.TextField(default='Name')),
                ('Need_power', models.BooleanField(default=False)),
                ('two_outlets', models.BooleanField(default=False)),
                ('table', models.BooleanField(default=False)),
                ('foamboard', models.BooleanField(default=False)),
                ('clips', models.BooleanField(default=False)),
                ('large_presentation', models.BooleanField(default=False)),
                ('sponsor_logos', models.BooleanField(default=False)),
                ('pictures', models.BooleanField(default=False)),
            ],
        ),
    ]
