# Generated by Django 5.1.1 on 2024-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniordesign',
            name='project_picture',
            field=models.ImageField(blank=True, null=True, upload_to='project_pictures/'),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='sponsor_logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/'),
        ),
    ]
