# Generated by Django 5.1.1 on 2024-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniordesign',
            name='Poster_tittle',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='large_presentaion',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='picutures',
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='Poster_title',
            field=models.CharField(default='untitled poster', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='large_presentation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='pictures',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Need_power',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Team_abbreviation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='clips',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='foamboard',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='sponsor_logos',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='table',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='team_member_names',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='two_outlets',
            field=models.BooleanField(),
        ),
    ]
