# Generated by Django 5.1.2 on 2024-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seniordesign_project_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seniordesign',
            old_name='clips',
            new_name='Need_more',
        ),
        migrations.RenameField(
            model_name='seniordesign',
            old_name='foamboard',
            new_name='easle',
        ),
        migrations.RenameField(
            model_name='seniordesign',
            old_name='large_presentation',
            new_name='foam',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Team_abbreviation',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='project_picture',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='sponsor_logo_image',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='two_outlets',
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='Any_additional_comments',
            field=models.TextField(default='Abstract', max_length=900),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='Brief_description',
            field=models.TextField(default='Abstract', max_length=900),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='Department',
            field=models.CharField(default='Department X', max_length=100),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='contact_email',
            field=models.TextField(default='Name'),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='sponsor_affiliation',
            field=models.TextField(default='Name'),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='sponsor_first_last_name',
            field=models.TextField(default='Name'),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Abstract',
            field=models.TextField(default='Abstract', max_length=900),
        ),
    ]
