# Generated by Django 5.1.1 on 2024-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_seniordesign_poster_tittle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniordesign',
            name='Abstract',
            field=models.TextField(default='Abstract'),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Location',
            field=models.CharField(default='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Need_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Poster_title',
            field=models.CharField(default='Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='Team_abbreviation',
            field=models.CharField(default='Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='clips',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='foamboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='large_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='num_team_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='pictures',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='sponsor_logos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='table',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='team_member_names',
            field=models.TextField(default='Name'),
        ),
        migrations.AlterField(
            model_name='seniordesign',
            name='two_outlets',
            field=models.BooleanField(default=False),
        ),
    ]
