# Generated by Django 5.1.1 on 2024-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_clips_seniordesign_need_more_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniordesign',
            name='Semester_Year',
            field=models.CharField(default='Fall 2024', max_length=100),
        ),
    ]
