# Generated by Django 5.1.2 on 2024-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seniordesign_semester_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_first_name', models.CharField(max_length=100)),
                ('sponsor_last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='seniordesign',
            old_name='Abstract',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='seniordesign',
            old_name='Need_more',
            new_name='ada_compliance',
        ),
        migrations.RenameField(
            model_name='seniordesign',
            old_name='Need_power',
            new_name='need_more',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Any_additional_comments',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Brief_description',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Poster_title',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='Semester_Year',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='num_team_members',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='sponsor_affiliation',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='sponsor_first_last_name',
        ),
        migrations.RemoveField(
            model_name='seniordesign',
            name='team_member_names',
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='additional_comments',
            field=models.TextField(blank=True, max_length=900),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='need_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='special_requirements',
            field=models.TextField(blank=True, max_length=900),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsored_projects', to='main.sponsor'),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='students',
            field=models.ManyToManyField(related_name='senior_design_projects', to='main.student'),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='department',
            field=models.CharField(default='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='poster_title',
            field=models.CharField(default='Poster Title', max_length=255),
        ),
        migrations.AddField(
            model_name='seniordesign',
            name='semester_year',
            field=models.CharField(default='Semester Year', max_length=100),
        ),
    ]
