name: Django and Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  check_run:
    types: [rerequested, completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Always succeed if no code yet
      - name: Always succeed
        run: exit 0

      # Uncomment the following steps when you have code
      # Python Setup (for Django)
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'  # Adjust if necessary

      # - name: Install Django dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run Django build (migrations and static files)
      #   run: |
      #     python manage.py migrate
      #     python manage.py collectstatic --noinput

      # Node.js Setup (for Angular)
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'  # Adjust to your project's Node version

      # - name: Install Angular dependencies
      #   run: |
      #     npm install  # Installs Angular dependencies

      # - name: Build Angular project
      #   run: |
      #     npm run build  # This will build the Angular frontend

      # Running your build and test scripts
      # - name: Run custom build script
      #   run: |
      #     chmod +x ./build.sh
      #     ./build.sh build

      # - name: Run custom test script
      #   run: |
      #     chmod +x ./test.sh
      #     ./test.sh
